const { buildProduccion, runProduccion } = require('./produccion');

module.exports = {
  getArticulo: require('./getArticulo.ts').default,
  getArticuloColorCodes: require('./getArticuloColorCodes.ts').default,
  getArticuloColorDistr: require('./getArticuloColorDistr.ts').default,
  getCambios: require('./getCambios.ts').default,
  getCurrArtColorDistr: require('./getCurrArtColorDistr.ts').default,
  buildProduccion,
  runProduccion,
  insertProgramada: require('./insertProgramada.js'),
  getProgramada: require('./getProgramada.js'),
  updateProgramada: require('./updateProgramada.js'),
  getProgramadaTotal: require('./getProgramadaTotal.js'),
  getProgColor: require('./getProgColor.js'),
  getMachines: require('./getMachines.js'),
  insertColorCodes: require('./insertColorCodes.js'),
  insertDistr: require('./insertDistr.js'),
  insertArticulo: require('./insertArticulo.js'),
  getProgColorTable: require('./getProgColorTable.js'),
  updateProgColorDoc: require('./updateProgColorDoc.js'),
  getProgActualDate: require('./getProgActualDate.js'),
  getProgLoadDates: require('./getProgLoadDates.js'),
  insertColor: require('./insertColor.js'),
  insertProgStartDate: require('./insertProgStartDate.js'),
  updateArticuloTipo: require('./updateArticulo.js'),
  getProductionsMonitor: require('./getProductionsMonitor.js'),
  getDailyProduction: require('./getDailyProduction.js'),
  getCurrWEff: require('./getCurrWEff.js'),
  getDailyWEff: require('./getDailyWEff.js'),
  getMonthSaldo: require('./getMonthSaldo.js'),
};
